import {useState} from 'react';
import type {EventDetail,LeagueRepository,MatchDetail} from '../domain/league';
import type {ViewProps} from './App';

export function MainPairingControls({data,repository,busy,act,onUpdated}:Pick<ViewProps,'repository'|'busy'|'act'>&{data:EventDetail;onUpdated:()=>void}) {
  const [mode,setMode]=useState<'RANDOM'|'ELO_BALANCED'>('RANDOM'),[reason,setReason]=useState(''),[attendance,setAttendance]=useState('');
  if(data.viewer.role!=='ADMIN')return null;
  const present=(data.signup.confirmed??[]).filter(p=>['CHECKED_IN','LATE_ADDED'].includes(p.attendanceStatus??''));
  const missing=data.signup.confirmedCount-present.length;
  const unresolved=(data.signup.confirmed??[]).filter(p=>!['CHECKED_IN','LATE_ADDED','NO_SHOW'].includes(p.attendanceStatus??'')).length+Math.max(0,data.signup.confirmedCount-(data.signup.confirmed??[]).length);
  const complete=unresolved===0;
  const draw=async(force:boolean)=>{if(await act(()=>repository.formEventMatches(data.event.eventId,{pairingMode:mode,force,reason}),'Main Battle draw prepared for review.'))onUpdated();};
  const plan=data.pairingPlan;
  return <details className="draft-admin"><summary>Emperor · main Battle pairing</summary><p>{present.length} checked in · {missing} missing. Only checked-in players enter the draw. Uneven teams follow Season standings.</p><label>Draw method<select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="RANDOM">Random teams</option><option value="ELO_BALANCED">Balance by League Elo</option></select></label><button disabled={busy||present.length<2||!complete} onClick={()=>void draw(false)}>{plan?.status==='PROPOSED'?'Draw again':'Draw main Battles'}</button>{unresolved>0&&!complete&&<><label>Reason to proceed with missing check-in<textarea minLength={8} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||present.length<2||reason.trim().length<8} onClick={()=>void draw(true)}>Force draw for checked-in players</button></>}{repository.markEventAttendance&&<fieldset><legend>Attendance exception · before main approval</legend><label>Player<select value={attendance} onChange={e=>setAttendance(e.target.value)}><option value="">Choose a confirmed player</option>{data.signup.confirmed?.map(p=><option key={p.playerId} value={p.playerId}>{p.steamName}</option>)}</select></label><label>Attendance reason<textarea maxLength={1000} minLength={8} value={reason} onChange={e=>setReason(e.target.value)}/></label>{(['LATE_ADDED','NO_SHOW'] as const).map(status=><button key={status} disabled={busy||!attendance||reason.trim().length<8} onClick={async()=>{if(await act(()=>repository.markEventAttendance!(data.event.eventId,attendance,status,reason),'Attendance exception recorded.'))onUpdated();}}>{status==='LATE_ADDED'?'Mark late arrival present':'Record no-show'}</button>)}</fieldset>}{plan?.status==='PROPOSED'&&<><p>Proposed draw · {plan.pairingMode==='RANDOM'?'Random':'League Elo'}</p>{plan.matches.map((match,i)=><p key={i}>{match.format.replaceAll('_',' ')}: {match.participants.map(p=>`${p.steamName}${p.team?` · side ${p.team}`:''}`).join(' / ')}</p>)}{!!plan.sittingOutPlayerIds.length&&<p>Sitting out: {plan.sittingOutPlayerIds.map(id=>(data.signup.confirmed??[]).find(p=>p.playerId===id)?.steamName??id).join(', ')}</p>}<button className="primary" disabled={busy||!repository.approveEventPairing} onClick={async()=>{if(await act(()=>repository.approveEventPairing!(data.event.eventId,plan.planId),'Main Battle pairings approved.'))onUpdated();}}>Approve this draw</button></>}</details>;
}

export function EmperorBattleControls({data,gameId,repository,onUpdated}:{data:MatchDetail;gameId:string;repository:LeagueRepository;onUpdated:()=>void}) {
  const game=data.games.find(g=>g.gameId===gameId)!;
  const [reason,setReason]=useState(''),[side,setSide]=useState(''),[winners,setWinners]=useState<string[]>([]),[verified,setVerified]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[starters,setStarters]=useState(data.match.participants.map(p=>p.playerId)),[names,setNames]=useState<Record<string,string>>({});
  const sourceHash=game.replay?.statisticsId,canReason=reason.trim().length>=8;
  const outcome=data.match.format==='FFA'?{winnerPlayerIds:winners}:{winnerTeam:Number(side)};
  const hasWinner=data.match.format==='FFA'?winners.length>0&&winners.length<game.players.length:side!=='';
  const perform=async(action:()=>Promise<void>)=>{setBusy(true);setError('');try{await action();onUpdated();}catch(e){setError(e instanceof Error?e.message:'The review could not be saved.');}finally{setBusy(false);}};
  const q=game.outcomeQualification;
  return <details className="draft-admin"><summary>Emperor · Battle controls</summary>{error&&<p role="alert">{error}</p>}<label>Review or exception reason<textarea maxLength={1000} minLength={8} value={reason} onChange={e=>setReason(e.target.value)}/></label>
    {sourceHash&&(!game.result||game.resultDisputeOpen)&&<div><p>{q?.reason??'Review the active recording and approved Battle settings.'}</p><label><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>I verified the winner, starter identities, announced settings and timely completion against the active recording.</label>{data.match.format==='FFA'?<fieldset><legend>Verified winner(s)</legend>{game.players.map(p=><label key={p.playerId}><input type="checkbox" checked={winners.includes(p.playerId)} onChange={e=>setWinners(e.target.checked?[...winners,p.playerId]:winners.filter(id=>id!==p.playerId))}/>{p.steamName}</label>)}</fieldset>:<label>Winning side<select value={side} onChange={e=>setSide(e.target.value)}><option value="">Choose the winner</option>{[...new Set(game.players.map(p=>p.team))].filter(t=>t!=null).map(t=><option key={t} value={t!}>Side {t}: {game.players.filter(p=>p.team===t).map(p=>p.steamName).join(', ')}</option>)}</select></label>}
      {!game.result&&<button disabled={busy||!verified||!canReason||!hasWinner||!repository.reviewRecordingResult} onClick={()=>perform(()=>repository.reviewRecordingResult!(data.match.matchId,gameId,sourceHash,outcome,reason,verified))}>Accept reviewed recording result</button>}
      {game.activeResultDisputeId&&<><button disabled={busy||!verified||!canReason||!hasWinner||!repository.resolveResultDispute} onClick={()=>perform(()=>repository.resolveResultDispute!(data.match.matchId,gameId,game.activeResultDisputeId!,'CORRECT',outcome,reason,sourceHash))}>Correct disputed result</button><button disabled={busy||!verified||!canReason||!repository.resolveResultDispute} onClick={()=>perform(()=>repository.resolveResultDispute!(data.match.matchId,gameId,game.activeResultDisputeId!,'UPHOLD',{},reason,sourceHash))}>Uphold existing result</button></>}
    </div>}
    {data.match.eventId&&sourceHash&&!game.result&&data.games.every(g=>!g.result)&&<button disabled={busy||!canReason||!repository.rejectUnresolvedEventMatch} onClick={()=>perform(()=>repository.rejectUnresolvedEventMatch!(data.match.matchId,reason))}>Reject invalid Battle without an accepted result</button>}
    {data.match.seriesRule&&data.match.seriesRule.maxGames>1&&<button disabled={busy||!canReason||!repository.finalizeSeries} onClick={()=>perform(()=>repository.finalizeSeries!(data.match.matchId,data.match.result?.revision??0,reason))}>Conclude series from accepted Games</button>}
    {data.match.status==='COMPLETED'&&data.match.processingState!=='COMPLETE'&&<button disabled={busy||!canReason||!repository.retryResultProcessing} onClick={()=>perform(()=>repository.retryResultProcessing!(data.match.matchId,reason))}>Retry pending result processing</button>}
    {data.match.status==='READY'&&!sourceHash&&!game.result&&<><fieldset><legend>Actual starters · before play and civilisation picks</legend>{data.match.participants.map(p=><label key={p.playerId}><input type="checkbox" checked={starters.includes(p.playerId)} onChange={e=>setStarters(e.target.checked?[...starters,p.playerId]:starters.filter(id=>id!==p.playerId))}/>{p.steamName}</label>)}</fieldset><button disabled={busy||!canReason||starters.length<2||!repository.confirmStarters} onClick={()=>perform(()=>repository.confirmStarters!(data.match.matchId,starters,reason))}>Confirm actual starters</button></>}
    {game.status==='READY'&&!sourceHash&&!game.result&&['READY','ACTIVE','AWAITING_CONFIRMATION'].includes(data.match.status)&&<><fieldset><legend>Resolve recording names · when Steam history cannot identify a starter</legend>{game.players.map(p=><label key={p.playerId}>{p.steamName}<input maxLength={100} placeholder="Exact name in the recording" value={names[p.playerId]??''} onChange={e=>setNames({...names,[p.playerId]:e.target.value})}/></label>)}</fieldset><button disabled={busy||!canReason||game.players.some(p=>!names[p.playerId]?.trim())||!repository.bindReplayParticipants} onClick={()=>perform(()=>repository.bindReplayParticipants!(data.match.matchId,gameId,game.players.map(p=>({playerId:p.playerId,sourceName:names[p.playerId]})),reason))}>Record verified identity bindings</button></>}
  </details>;
}
