import {useState} from 'react';
import type {ViewProps} from './App';
import {civilizationCatalogue} from '../data/civilizations';
export function EmperorCampaignControls({snapshot,repository,busy,act,openEvent,preview}:ViewProps) {
  const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[date,setDate]=useState(''),[map,setMap]=useState('Arabia'),[warmupMap,setWarmupMap]=useState('Arabia'),[style,setStyle]=useState('BIG_TEAM'),[draft,setDraft]=useState(false),[standard,setStandard]=useState(false),[max,setMax]=useState(8),[completionGold,setCompletionGold]=useState(0),[winGold,setWinGold]=useState(0);
  if(snapshot.viewer?.role!=='ADMIN'||preview)return null;
  return <details className="panel"><summary>Emperor · prepare a new Event</summary><form className="form" onSubmit={async e=>{
    e.preventDefault();let eventId='';
    const startsAt=new Date(date),checkInOpensAt=new Date(startsAt.getTime()-30*60000);
    const gameConfig={maps:{pool:[map.trim()],selectionMode:'ADMIN'},civilizations:draft?{mode:'DRAFT',allowed:civilizationCatalogue.map(c=>c.id),banned:[],customRuleCode:null,draft:{ruleVersion:'AOF_CIV_DRAFT_V1',turnOrder:'RANDOM',reusePolicy:'RESET_EACH_GAME',uniqueWithinGame:true}}:{mode:'UNRESTRICTED',allowed:[],banned:[],customRuleCode:null},victory:{conquest:true,wonder:standard,relic:standard,customRuleCode:null},diplomacyEnabled:false,additionalSettings:{}};
    const warmupConfig={...gameConfig,maps:{pool:[warmupMap.trim()],selectionMode:'ADMIN'},civilizations:{mode:'UNRESTRICTED',allowed:[],banned:[],customRuleCode:null},victory:{conquest:true,wonder:false,relic:false,customRuleCode:null}};
    if(await act(async()=>{const result=await repository.createEvent!({title,description,startsAt:startsAt.toISOString(),signupDeadlineAt:checkInOpensAt.toISOString(),checkInOpensAt:checkInOpensAt.toISOString(),checkInClosesAt:startsAt.toISOString(),timezone:'Europe/Copenhagen',minParticipants:2,maxParticipants:max,waitingListEnabled:true,signupRosterVisibility:'VISIBLE',competitionStyle:style,planningConfig:{pairingMode:'RANDOM',allowAsymmetricTeams:true,prioritizeLargestTeams:true,preferredTeamSize:4},gameConfig,warmupPolicy:{gameConfig:warmupConfig},placementPolicy:style==='FFA'?'ELIMINATION_ORDER':'NONE',goldRewardSnapshot:{attendance:0,matchCompletion:completionGold,matchWin:winGold}});eventId=result.eventId;},'Event draft saved. Review it before publishing.'))openEvent(eventId);
  }}><p>Warm-ups are drawn seven days before the Event. Check-in opens thirty minutes before kickoff. The draft is saved for review before publication.</p><label>Event title<input required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Campaign briefing<textarea maxLength={5000} value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Main Event · local date and time<input required type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Format<select value={style} onChange={e=>setStyle(e.target.value)}><option value="BIG_TEAM">Largest teams</option><option value="TWO_V_TWO">2v2 Battles</option><option value="ONE_V_ONE">1v1 Battles</option><option value="FFA">Fixed FFA · no diplomacy</option></select></label><label>Main map<input required maxLength={80} value={map} onChange={e=>setMap(e.target.value)}/></label><label>Warm-up map<input required maxLength={80} value={warmupMap} onChange={e=>setWarmupMap(e.target.value)}/></label><label>Participant limit<input type="number" min={2} max={100} value={max} onChange={e=>setMax(Number(e.target.value))}/></label><label><input type="checkbox" checked={draft} onChange={e=>setDraft(e.target.checked)}/>Draft unique civilisations from the full catalogue</label><label><input type="checkbox" checked={standard} onChange={e=>setStandard(e.target.checked)}/>Allow Standard Victory (conquest, wonder and relic)</label><p>League points follow the Season rules. Gold is configured separately for each Battle.</p><label>Completion Gold<input type="number" min={0} max={1000} value={completionGold} onChange={e=>setCompletionGold(Number(e.target.value))}/></label><label>Victory Gold<input type="number" min={0} max={1000} value={winGold} onChange={e=>setWinGold(Number(e.target.value))}/></label><button className="primary" disabled={busy||!repository.createEvent}>Save Event draft</button></form></details>;
}
