import {useState} from 'react';
import {ArrowRight,BookOpen,Users,Crown,Check,Lock,Swords,Flag,Heart,Search,Shield,Upload} from 'lucide-react';
import {LeagueEvent,LeagueService,RelationshipPolicy,formatName,isLombardia,type EventDetail,type MatchDetail,type PlayerProfile} from '../domain/league';
import {plannedEvents,lombardia} from '../data/content';
import {Avatar,DateLabel,Empty,Roster,Sigil} from './Primitives';
import type {ViewProps} from './App';

export function SeasonView(props:ViewProps&{onRules:()=>void}){
  const {snapshot:s,preview,busy,repository,openEvent,openMatch,openPlayer,act,enter,navigate,onRules}=props;
  const service=new LeagueService(repository);
  const next=s.events.find(e=>e.status==='ACTIVE')??s.events.find(e=>e.status==='PUBLISHED'&&(!e.startsAt||Date.parse(e.startsAt)>=Date.now()));
  const warmup=next&&s.matches.find(m=>m.eventId===next.eventId&&m.format==='ONE_V_ONE'&&m.participants.some(p=>p.playerId===s.viewer?.playerId));
  const main=next&&s.matches.find(m=>m.eventId===next.eventId&&m.format!=='ONE_V_ONE'&&m.participants.some(p=>p.playerId===s.viewer?.playerId));
  const viewerIsEmperor=!!s.viewer&&s.viewer.playerId===s.emperor?.playerId;
  const own=viewerIsEmperor?s.emperor:s.standings.find(p=>p.playerId===s.viewer?.playerId),target=service.nextTarget(s),points=own?.leaguePoints??0,targetPoints=target?.leaguePoints??0;
  const progress=targetPoints>0?Math.min(100,Math.max(0,points/targetPoints*100)):0;
  const rsvp=(value:'YES'|'NO')=>{if(!next)return;if(s.membership!=='ACTIVE'||value==='YES'&&!s.enteredSeason){enter();return;}void act(()=>service.rsvp(s,next.eventId,value),'Your event response has been saved.');};
  return <>
    <div className="section-heading season-heading"><div><span className="eyebrow">SEASON I</span><h1>{s.season?.name??'The Fiefdom of Bad Neighbors'}</h1></div><button className="text-button" onClick={onRules}><BookOpen size={16}/>Season rules</button></div>
    <section className="schedule-section"><div className="section-heading"><h2>Event schedule</h2><button className="text-button" onClick={()=>navigate('events')}>All events<ArrowRight size={15}/></button></div><div className="schedule">{s.events.map((e,i)=><button key={e.eventId} className={e.eventId===next?.eventId?'next':''} onClick={()=>openEvent(e.eventId)}><span className="eyebrow">{e.startsAt?new Date(e.startsAt).toLocaleDateString(undefined,{month:'short',day:'numeric'}):'DATE TBA'}</span><i/><strong>{e.title}</strong><small>{isLombardia(e)?'4v4':formatName(e.competitionStyle)}{e.eventId===next?.eventId?' · NEXT':''}</small></button>)}{plannedEvents.map(e=><button key={e.id} onClick={()=>navigate('events')}><span className="eyebrow">{e.period}</span><i/><strong>{e.title}</strong><small>{e.format}</small></button>)}</div></section>
    {next?<section className="next-event panel">
      <div className="event-intro"><div className="event-title"><Sigil kind="flag" size={32}/><div><span className="eyebrow">NEXT EVENT</span><h2>{next.title}</h2></div></div><div className="countdown"><strong>{new LeagueEvent(next).countdown()}</strong></div></div>
      <div className="acts"><div className="act"><Sigil kind="duel"/><div><span className="eyebrow">ACT I · YOUR WARM-UP</span><h3>{warmup?<button className="text-button" onClick={()=>openMatch(warmup.matchId)}>{warmup.participants.filter(p=>p.playerId!==s.viewer?.playerId).map(p=>p.steamName).join(' · ')}<ArrowRight size={15}/></button>:'Opponent to be revealed'}</h3><p>1v1 · Approximately 30 minutes</p></div></div><div className="act"><Sigil/><div><span className="eyebrow">ACT II · MAIN EVENT</span><h3>{main?<button className="text-button" onClick={()=>openMatch(main.matchId)}>{formatName(main.format)} · View your match<ArrowRight size={15}/></button>:isLombardia(next)?'4v4 · Eight banners':formatName(next.competitionStyle)}</h3><p>{main?'Approved Game plan · Teams revealed':isLombardia(next)?'Lombardia · Standard Victory':'Final format follows the approved plan'}</p></div></div></div>
      <div className="event-footer"><span className="attendance"><Users size={16}/>{next.confirmedCount??0} / {next.maxParticipants??'—'} banners raised{next.viewer?.rsvp==='YES'&&<span className="confirmed"><Check size={14}/>{next.viewer.signupState==='WAITING_LIST'?'Waiting list':'You’re in'}</span>}{next.viewer?.rsvp==='NO'&&<span>You declined</span>}</span><div className="actions"><button className="text-button" onClick={()=>openEvent(next.eventId)}>Event details<ArrowRight size={15}/></button>{new LeagueEvent(next).canRsvp()&&<><button className="text-button" disabled={busy||next.viewer?.rsvp==='NO'} onClick={()=>rsvp('NO')}>Decline</button><button className="primary" disabled={busy||next.viewer?.rsvp==='YES'} onClick={()=>rsvp('YES')}>{next.viewer?.rsvp==='YES'?'Banner raised':s.enteredSeason?'I’m in':'Enter season'}</button></>}</div></div>
    </section>:<section className="panel"><Empty title="The next muster is being prepared">Published events will appear here when announced.</Empty></section>}
    <section className="standings-section"><div className="section-heading"><h2>Season standing</h2><span className="eyebrow">{preview?'ILLUSTRATIVE STANDINGS':'THE THRONE · PLAYER LADDER'}</span></div><div className="panel standings">{s.emperor&&<section className="emperor-seat" aria-label={'Emperor '+s.emperor.steamName}><div className="emperor-office"><Crown size={24}/><span><span className="eyebrow">THE THRONE</span><strong>Emperor</strong></span></div><button className="emperor-identity" onClick={()=>openPlayer(s.emperor!.playerId)}><Avatar player={s.emperor}/><span><strong>{s.emperor.steamName}</strong><small>Fixed office · outside player ranking</small></span></button><div className="emperor-record"><span><small>W–L</small><strong>{s.emperor.wins!=null&&s.emperor.losses!=null?s.emperor.wins+'–'+s.emperor.losses:'—'}</strong></span><span><small>Points</small><strong>{s.emperor.leaguePoints??0}</strong></span></div></section>}<div className="player-ladder-label"><span className="eyebrow">PLAYER LADDER</span><span>Rank changes with league points</span></div><table><thead><tr><th scope="col" className="rank">#</th><th scope="col">Player</th><th scope="col" className="record">W–L</th><th scope="col" className="points">Points</th></tr></thead><tbody>{s.standings.map((p,i)=><tr key={p.playerId} className={p.playerId===s.viewer?.playerId?'you':''}><td className={'rank '+(i===0?'gold':'')}>{p.rank??i+1}</td><th scope="row"><button className="player-link" onClick={()=>openPlayer(p.playerId)}><Avatar player={p}/><span>{p.steamName}</span>{p.playerId===s.viewer?.playerId&&<small>YOU</small>}</button></th><td className="record">{p.wins!=null&&p.losses!=null?p.wins+'–'+p.losses:'—'}</td><td className="points">{p.leaguePoints??0}</td></tr>)}</tbody></table>
      {!s.standings.length&&<Empty title="The player ladder awaits">The first qualified player results will establish the standings.</Empty>}
      <div className="progression">{s.viewer&&s.enteredSeason?<><div><span className="eyebrow">YOUR SEASON</span><strong>{points} <small>LEAGUE POINTS</small></strong></div><div className="progress-target">{viewerIsEmperor?<><span className="eyebrow">IMPERIAL OFFICE</span><p>Your place is fixed above the ladder. Your matches still count as competitive league results.</p></>:target?<><span className="eyebrow">NEXT TARGET · {target.steamName}</span><div className="target-line"><span style={{width:progress+'%'}}/></div><p>{Math.max(0,targetPoints-points)} points to draw level</p></>:<p>{s.standings[0]?.playerId===s.viewer.playerId?'You lead the player ladder.':'Your first qualified result begins your climb.'}</p>}</div></>:<><div><span className="eyebrow">YOUR SEASON</span><p>Raise your banner. Take your place.</p></div><button className="text-button gold" onClick={enter}>Enter Season I<ArrowRight size={16}/></button></>}</div>
    </div></section>
  </>;
}
export function EventsView({snapshot,openEvent}:ViewProps){
  return <section className="section"><div className="section-heading"><div><span className="eyebrow">SEASON I</span><h1>The campaign</h1></div><span className="muted">One season. Many battlefields.</span></div><div className="event-list">
    {snapshot.events.map((e,i)=><article key={e.eventId} className="panel event-list-card"><span className="event-number">{String(i+1).padStart(2,'0')}</span><Sigil kind="flag" size={32}/><div><span className="eyebrow">{e.status.replaceAll('_',' ')}</span><h2>{e.title}</h2><p>{isLombardia(e)?lombardia.display.formatLine:formatName(e.competitionStyle)}</p><p className="muted"><DateLabel value={e.startsAt}/></p></div><button className="primary" onClick={()=>openEvent(e.eventId)}>View event<ArrowRight size={16}/></button></article>)}
    {plannedEvents.map((e,i)=><article className="panel event-list-card planned" key={e.id}><span className="event-number">{String(i+2).padStart(2,'0')}</span><Sigil kind={i?'ffa':'team'} size={32}/><div><span className="eyebrow">{e.period} · PLANNED</span><h2>{e.title}</h2><p>{e.format}</p><p className="muted">{e.description}</p></div><span className="quiet-badge">Details to come</span></article>)}
  </div><p className="footnote">Later event details are provisional. Final dates and rules will be announced with each event.</p></section>;
}
export function BattlesView({snapshot,openMatch}:ViewProps){
  const [query,setQuery]=useState(''),[filter,setFilter]=useState('all');
  const matches=snapshot.matches.filter(m=>(filter==='all'||(filter==='mine'?m.participants.some(p=>p.playerId===snapshot.viewer?.playerId):filter==='completed'?m.status==='COMPLETED':['READY','ACTIVE','AWAITING_CONFIRMATION'].includes(m.status)))&&(m.matchId+' '+m.format+' '+m.participants.map(p=>p.steamName).join(' ')).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(a.completedAt??'9999').localeCompare(b.completedAt??'9999'));
  return <section className="section"><div className="section-heading"><div><span className="eyebrow">THE BATTLE ARCHIVE</span><h1>Every encounter leaves a mark</h1></div></div><div className="filter-bar"><label className="search"><Search size={18}/><input aria-label="Search battles" placeholder="Search player or battle…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter battles" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All battles</option><option value="mine">My battles</option><option value="upcoming">Upcoming & underway</option><option value="completed">Completed</option></select></div><div className="panel">
    {!matches.length?<Empty title={query||filter!=='all'?'No matching battles':'The battlefield is quiet'} icon="duel">{query||filter!=='all'?'Try another player or change the filter.':'Your approved warm-up and main-event matches will appear here after check-in and match-plan approval.'}</Empty>:matches.map(m=><button className="battle-row" key={m.matchId} onClick={()=>openMatch(m.matchId)}><Sigil kind={m.format==='ONE_V_ONE'?'duel':'team'}/><span><span className="eyebrow">{formatName(m.format)} · {m.status.replaceAll('_',' ')}</span><strong>{m.participants.map(p=>p.steamName).join(' · ')}</strong><small>{m.matchId}{m.completedAt&&<> · <DateLabel value={m.completedAt}/></>}</small></span><ArrowRight size={18}/></button>)}
  </div></section>;
}
export function PlayersView({snapshot,openPlayer}:ViewProps){
  const [query,setQuery]=useState('');const players=snapshot.players.filter(p=>p.steamName.toLowerCase().includes(query.toLowerCase()));
  return <section className="section"><div className="section-heading"><div><span className="eyebrow">THE LEAGUE ROSTER</span><h1>The people behind the banners</h1></div><label className="search"><Search size={18}/><input aria-label="Search players" placeholder="Find a player…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="player-grid">
    {players.map((p,i)=><button className={'portrait-card banner-'+i%4} key={p.playerId} onClick={()=>openPlayer(p.playerId)}><div className="portrait-door"><Shield size={72} strokeWidth={.6}/><Avatar player={p} large/><span className="door-line"/></div><div className="portrait-caption"><span className="eyebrow">LEAGUE MEMBER</span><h2>{p.steamName}</h2><span className="profile-hint">Open profile<ArrowRight size={14}/></span></div></button>)}
  </div>{!players.length&&<Empty title="No players found">Try another name.</Empty>}<p className="footnote">Portraits begin as a newcomer identity. Earned military identities will follow validated match evidence.</p></section>;
}
export function WarRoomView(){
  return <section className="section war-room"><div className="war-heading"><span className="eyebrow">SOME THINGS ARE PERSONAL</span><Lock size={34} strokeWidth={1}/><h1>The War Room</h1><p>The doors remain closed.</p><span className="quiet-badge">PROGRESSION AWAITING VALIDATED STATISTICS</span></div><div className="war-intro"><h2>Respect. Rivalry. Retribution.</h2><p>Reach the third stage of Rivalry or Enemy with another player to unlock your War Room. Friendships and rivalries can grow side by side.</p></div><div className="relationship-grid">
    {RelationshipPolicy.tracks.map((t,i)=>{const Icon=i===0?Swords:i===1?Flag:Heart;return <article className={'relationship-track track-'+i} key={t.name}><Icon size={26} strokeWidth={1.2}/><span className="eyebrow">{t.axis}</span><h2>{t.name}</h2><p>{t.description}</p><ol>{t.stages.map((stage,j)=><li key={stage} className={j===2&&i<2?'unlock-stage':''}><span>{String(j+1).padStart(2,'0')}</span>{stage}{j===2&&i<2&&<Lock size={13}/>}</li>)}</ol></article>;})}
  </div><div className="war-footer"><Shield size={20}/><p>Challenges have separate season and all-time standings. War Room Points never count as League Points.</p></div></section>;
}
export function StatisticsView(){
  const [scope,setScope]=useState('season'),[category,setCategory]=useState('Economy');
  const groups:Record<string,{label:string;description:string}[]>={
    Economy:[{label:'Economy & tribute',description:'Qualified economy and support measures will appear here.'},{label:'Age progression',description:'Observed age timings will be distinguished from estimates.'}],
    Military:[{label:'Military production',description:'Completed units need evidence beyond a queue request.'},{label:'Fights & raids',description:'Combat and raid estimates are awaiting validation.'}],
    'Map Presence':[{label:'Map activity',description:'Spatial activity will carry its evidence and coverage.'},{label:'Pressure & support',description:'Directed interaction measures are still being qualified.'}],
    Execution:[{label:'Player commands',description:'Command counts exist in the extraction foundation; the player-facing contract is pending.'},{label:'Research requests',description:'Research requests do not prove an age was reached.'}]
  };
  const categories=Object.keys(groups);
  return <section className="section"><div className="section-heading"><div><span className="eyebrow">BEHIND THE BATTLES</span><h1>League statistics</h1></div><select aria-label="Statistics scope" value={scope} onChange={e=>setScope(e.target.value)}><option value="season">This season</option><option value="recent">Recent games</option><option value="lifetime">Lifetime</option></select></div><div className="stats-note"><Shield size={21}/><div><strong>Every statistic needs a battle behind it.</strong><p>Replay statistics are being qualified. Unavailable values stay empty; they are never treated as zero.</p></div></div><div className="category-tabs" role="tablist" aria-label="Statistics categories">
    {categories.map((c,i)=><button key={c} id={'category-'+i} role="tab" aria-selected={category===c} aria-controls="statistics-panel" tabIndex={category===c?0:-1} className={category===c?'active':''} onClick={()=>setCategory(c)} onKeyDown={e=>{let index=i;if(e.key==='ArrowRight')index=(i+1)%categories.length;else if(e.key==='ArrowLeft')index=(i+categories.length-1)%categories.length;else if(e.key==='Home')index=0;else if(e.key==='End')index=categories.length-1;else return;e.preventDefault();setCategory(categories[index]);document.getElementById('category-'+index)?.focus();}}>{c}</button>)}
    </div><div id="statistics-panel" role="tabpanel" aria-labelledby={'category-'+categories.indexOf(category)} className="stat-grid">{groups[category].map(m=><article className="panel stat-card" key={m.label}><span className="eyebrow">{scope==='season'?'THIS SEASON':scope==='recent'?'RECENT GAMES':'LIFETIME'}</span><h2>{m.label}</h2><strong className="stat-unavailable">—</strong><span className="quiet-badge">Awaiting qualified data</span><p>{m.description}</p></article>)}</div><div className="section-heading"><h2>Achievements, awards & trophies</h2></div><div className="panel"><Empty title="Distinctions must be earned">Definitions and earning rules are pending reliable statistics. Selected achievements will appear on profiles; full collections remain private.</Empty></div></section>;
}
export function EventDialog(props:ViewProps&{data:EventDetail;onUpdated:()=>void}){
  const {data,snapshot,busy,repository,act,enter,onUpdated,openMatch}=props;
  const event=new LeagueEvent({...data.event,viewer:data.viewer});
  const respond=async(value:'YES'|'NO')=>{
    if(snapshot.membership!=='ACTIVE'||value==='YES'&&!snapshot.enteredSeason){enter();return;}
    const fresh={...snapshot,events:[...snapshot.events.filter(e=>e.eventId!==event.id),{...data.event,viewer:data.viewer}]};
    if(await act(()=>new LeagueService(repository).rsvp(fresh,event.id,value),'Your event response has been saved.'))onUpdated();
  };
  return <><div className="detail-meta"><span className="quiet-badge">{data.event.status.replaceAll('_',' ')}</span><span><DateLabel value={data.event.startsAt}/></span></div><p>{data.event.description??''}</p><div className="detail-acts"><div><Sigil kind="duel"/><span className="eyebrow">ACT I · WARM-UP</span><h3>1v1 · 30 minutes</h3><p>Pairings follow the approved match plan.</p></div><div><Sigil/><span className="eyebrow">ACT II · MAIN EVENT</span><h3>{isLombardia(data.event)?'4v4 · Lombardia':formatName(data.event.competitionStyle)}</h3><p>The final Game shape follows attendance.</p></div></div>
    <div className="section-heading"><h3>The muster</h3><span className="muted">{data.signup.confirmedCount} confirmed · {data.signup.waitingListCount} waiting</span></div>
    {data.signup.rosterVisible?<Roster players={data.signup.confirmed??[]}/>:<p className="muted">The roster will be revealed by the event organizer.</p>}
    <div className="participation-status"><Check size={17}/>{data.viewer.attendanceStatus==='CHECKED_IN'?'You are checked in.':data.viewer.rsvp==='YES'?data.viewer.signupState==='WAITING_LIST'?'You are on the waiting list.':'Your banner is raised.':data.viewer.rsvp==='NO'?'You have declined this event.':'You have not answered this event yet.'}</div>
    <div className="actions">{event.canRsvp()&&<><button className="primary" disabled={busy||data.viewer.rsvp==='YES'} onClick={()=>void respond('YES')}>{snapshot.enteredSeason?'I’m in':'Enter season first'}</button><button className="text-button" disabled={busy||data.viewer.rsvp==='NO'} onClick={()=>void respond('NO')}>Decline</button></>}
      {event.canCheckIn()?<button className="primary" disabled={busy} onClick={async()=>{if(await act(()=>repository.checkIn(event.id),'You are checked in.'))onUpdated();}}>Check in</button>:data.viewer.attendanceStatus!=='CHECKED_IN'&&<span className="muted">{data.event.checkInOpensAt?<>Check-in opens <DateLabel value={data.event.checkInOpensAt}/></>:'Check-in time to be announced'}</span>}
    </div><hr/><h3>Matches & civilization draft</h3>{data.matches.filter(m=>m.status!=='PROPOSED').map(m=><button className="battle-row" key={m.matchId} onClick={()=>openMatch(m.matchId)}><Sigil kind="duel"/><span><strong>{formatName(m.format)} · {m.matchId}</strong><small>{m.participants.map(p=>p.steamName).join(' · ')}</small></span><ArrowRight size={17}/></button>)}
    <p className="muted">{!data.matches.length?'Matches will be revealed after check-in and plan approval. ':''}The civilization draft is not yet available.</p>
  </>;
}
export function MatchDialog({data,busy,repository,act,onUpdated}:ViewProps&{data:MatchDetail;onUpdated:()=>void}){
  const [dispute,setDispute]=useState<string|null>(null),[reason,setReason]=useState(''),[category,setCategory]=useState('WRONG_RESULT');
  return <><div className="detail-meta"><span className="eyebrow">{formatName(data.match.format)} · {data.match.matchId}</span><span className="quiet-badge">{data.match.status.replaceAll('_',' ')}</span></div><Roster players={data.match.participants}/>
    {data.games.map(game=><article className="game-panel" key={game.gameId}><div className="section-heading"><h3>Game {game.gameNumber}</h3>{data.viewer.isParticipant&&game.result&&!game.resultDisputeOpen&&game.status==='COMPLETED'&&<button className="text-button small" onClick={()=>setDispute(dispute===game.gameId?null:game.gameId)}>Dispute result</button>}</div><div className="game-players">{game.players.map(p=><div key={p.playerId}><Avatar player={p}/><span><strong>{p.steamName}</strong><small>{p.civilization??'Civilization not yet selected'}{p.team!=null?' · Team '+p.team:''}</small></span>{!game.resultDisputeOpen&&game.result?.winningPlayerIds.includes(p.playerId)&&<span className="gold">Winner</span>}</div>)}</div><p className={game.resultDisputeOpen?'disputed':'muted'}>{game.resultDisputeOpen?'Result under correction review.':game.result?'Final result · Revision '+game.result.revision:'Awaiting a qualified result.'}</p>
      {dispute===game.gameId&&<form className="form dispute-form" onSubmit={async e=>{e.preventDefault();if(await act(()=>repository.dispute(data.match.matchId,game.gameId,category,reason.trim()),'Dispute submitted for review.')){setDispute(null);onUpdated();}}}><label>What needs correcting?<select value={category} onChange={e=>setCategory(e.target.value)}><option value="WRONG_RESULT">Wrong result</option><option value="WRONG_REPLAY">Wrong replay</option><option value="PLAYER_MISMATCH">Player mismatch</option><option value="OTHER">Other</option></select></label><label>Reason<textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="primary" disabled={busy||!reason.trim()}>Submit dispute</button></form>}
      <div className="upload-state"><Upload size={23}/><div><strong>Replay submission is not available yet</strong><p>Keep the .aoe2record on your computer. Uploading and automatic processing will be enabled when ready.</p></div></div>
    </article>)}
    {!data.games.length&&<Empty title="The Game plan is not ready">Your Games will appear after the match plan is approved.</Empty>}
  </>;
}
export function ProfileDialog({data,snapshot,preview}:ViewProps&{data:PlayerProfile}){
  const [scope,setScope]=useState('season'),own=data.player.playerId===snapshot.viewer?.playerId;
  const stats=scope==='season'?data.activeSeason?.competition:data.lifetime.competition;
  const values:[string,string|number|null|undefined][]=[['Played',stats?.matchesPlayed],['Won',stats?.matchesWon],['Lost',stats?.matchesLost],['Win rate',stats&&stats.matchesPlayed>0?Math.round(stats.matchesWon/stats.matchesPlayed*100)+'%':null]];
  return <><div className="profile-overview"><div className="profile-portrait"><Avatar player={data.player} large/><span className="eyebrow">NEWCOMER</span></div><div><span className="eyebrow">PERSISTENT LEAGUE IDENTITY</span><h3>{data.player.steamName}</h3><p>Your banner outlives a single season.</p><span className="quiet-badge">Military identity awaiting qualified evidence</span></div></div>
    <div className="section-heading"><h3>Battle record{preview?' · Sample':''}</h3><select aria-label="Player record scope" value={scope} onChange={e=>setScope(e.target.value)}><option value="season">This season</option><option value="lifetime">Lifetime</option></select></div><div className="profile-record">{values.map(([label,value])=><div key={label}><strong>{value??'—'}</strong><span>{label}</span></div>)}</div>
    <h3>Selected achievements</h3>{data.achievements.length?<div className="achievements">{data.achievements.slice(0,3).map(a=><div key={a.awardId}><Shield size={22}/><strong>{a.name}</strong><p>{a.description}</p></div>)}</div>:<p className="muted">No achievements are showcased. Achievement rules are awaiting validated statistics.</p>}{own&&<p className="footnote">Your full collection and personal progression belong only to you.</p>}<hr/><h3>Shared history</h3><div className="history-columns"><section><span className="eyebrow">ACROSS THE BATTLEFIELD</span>{data.opponents.length?data.opponents.map(r=><p key={r.player.playerId}>{r.player.steamName}<span>{r.matchesTogether} encounters</span></p>):<p className="muted">No recorded opponents yet.</p>}</section><section><span className="eyebrow">UNDER ONE BANNER</span>{data.teammates.length?data.teammates.map(r=><p key={r.player.playerId}>{r.player.steamName}<span>{r.matchesTogether} together</span></p>):<p className="muted">No recorded teammates yet.</p>}</section></div><p className="footnote">Rivalry, Enemy and Friend progression will be drawn from validated battle evidence.</p>
  </>;
}
